steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['run', 'build']
    env:
      - 'REACT_APP_BACKEND_URL=${_BACKEND_URL}' # Substitute backend URL during build

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: ['build', '-t', 'REGION-docker.pkg.dev/euphrates-pacesetters/frontend/pacesetter-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'REGION-docker.pkg.dev/euphrates-pacesetters/frontend/pacesetter-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - secure-frontend
      - --image=REGION-docker.pkg.dev/euphrates-pacesetters/frontend/pacesetter-app
      - --region=REGION
      - --platform=managed
      - --allow-unauthenticated
      - --port=80
    env:
      - _BACKEND_URL=${_BACKEND_URL} # Pass the backend URL to the deploy command

substitutions:
  _BACKEND_URL: 'DEPLOYED_BACKEND_URL' # You'll provide this during trigger creation or gcloud command

images:
  - REGION-docker.pkg.dev/euphrates-pacesetters/frontend/pacesetter-app