options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/euphrates-pacesetters/frontend/pacesetter-app', '.']
    env:
      - 'REACT_APP_BACKEND_URL=${_BACKEND_URL}' # Pass environment variable during Docker build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/euphrates-pacesetters/frontend/pacesetter-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - secure-frontend
      - --image=europe-west1-docker.pkg.dev/euphrates-pacesetters/frontend/pacesetter-app
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated
      - --port=80
    env:
      - _BACKEND_URL=${_BACKEND_URL} # Pass the backend URL to the deploy command

substitutions:
  _BACKEND_URL: 'https://secure-backend-289242285061.europe-west1.run.app'

images:
  - europe-west1-docker.pkg.dev/euphrates-pacesetters/frontend/pacesetter-app