build:
  options:
    logging: CLOUD_LOGGING_ONLY
    
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/euphrates-pacesetters/backend/pacesetter-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/euphrates-pacesetters/backend/pacesetter-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - secure-backend
      - --image=europe-west4-docker.pkg.dev/euphrates-pacesetters/backend/pacesetter-app
      - --region=europe-west4
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080

images:
  - europe-west4-docker.pkg.dev/euphrates-pacesetters/backend/pacesetter-app
